### ISSUE TITLE
self.version is not canonical.

### ISSUE THREAD

**Issue by ioquatix** [HornsAndHooves/lazy_object#2]
The usual form is to have a constant defined e.g. `LazyObject::VERSION` - is there any reason why it isn't done like this?

**Comment by albertosaurus** [comment]
"Canonical" is a pretty strong term. I've come across a whole bunch of different ways a gem version is defined (or not defined, for that matter). In general, I'm not a fan of Ruby constants for reasons which are probably beyond the scope of your question. If you have a strong reason why you want a `VERSION` constant, I think we may be willing to accommodate.

**Comment by ioquatix** [comment]
Just because it's what most gems do, but you are right not all gems do it:

```
[1] pry(main)> require 'mysql2'                                                 
=> true
[2] pry(main)> Mysql2::VERSION                                                  
=> "0.4.2"
[3] pry(main)> require 'celluloid'                                              
I, [2015-12-06T13:18:36.625360 #43050]  INFO -- : Celluloid 0.17.2 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
=> true
[4] pry(main)> Celluloid::VERSION                                               
=> "0.17.2"
[5] pry(main)> require 'rspec'                                                  
=> true
[6] pry(main)> RSpec::VERSION                                                   
NameError: uninitialized constant RSpec::VERSION
from /Users/samuel/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.1/lib/rspec/core.rb:178:in `block in const_missing'
```

Another thing to consider is this is the default behaviour for new gems generated by bundler:

```
> bundle gem foo
Creating gem 'foo'...
      create  foo/Gemfile
      create  foo/.gitignore
      create  foo/lib/foo.rb
      create  foo/lib/foo/version.rb
      create  foo/foo.gemspec
      create  foo/Rakefile
      create  foo/README.md
      create  foo/bin/console
      create  foo/bin/setup
      create  foo/.travis.yml
      create  foo/.rspec
      create  foo/spec/spec_helper.rb
      create  foo/spec/foo_spec.rb
Initializing git repo in /private/tmp/foo
> cat foo/lib/foo/version.rb   
module Foo
  VERSION = "0.1.0"
end
```

**Comment by albertosaurus** [comment]
Right. So, what are you doing that's making the lack of a `VERSION` constant bothersome?

**Comment by ioquatix** [comment]
Nothing, it's just not canonical. Sometimes it's useful.

**Comment by djberg96** [comment]
It is considered a best practice: http://weblog.rubyonrails.org/2009/9/1/gem-packaging-best-practices/

It should also probably be frozen.

**Comment by ioquatix** [comment]
@djberg96 Haha, think of the children. `VERSION.replace("#{rand}.#{rand}.#{rand}")`

**Comment by baburdick** [comment]
@ioquatix: feel free to submit a pull request. Good working code, passing specs, no newly uncovered lines, and we'll be happy to merge.

Not averse to best practices. But it sucks when they're simply assertions without clear reasoning backing up why the practice is superior. It erodes confidence in the system of best practices when "Why is this practice the best?" is a hard question.

**Comment by ioquatix** [comment]
I opened this issue 2 years ago and I'm not using this gem any more, so I can't really justify spending the time making a PR but as a matter of taking the time explain why I think it's best practice, I'm happy to provide some feedback.

There are a couple of reasons I can think of why a version constant is probably the right thing to do and recommended as a best practice:

1/ Almost everyone does it using a constant (principle of least surprise)
2/ It's more efficient (invoking a method is more expensive than looking up a constant).
3/ Although a less strong argument, a method should probably do something, rather than returning a constant that would never change. The exception to this would be if you were implementing an interface.

I actually don't really mind that much. If you note the language in my original issue, I just asked why it was done differently but the response was sort of like "We have reasons but we can't explain them". The issue is when I load up a gem and I want to quickly know what version I'm using in `pry` for example, 99% of gems I can just write `GemName::VERSION`. But at the time, for this gem, it wasn't possible. What should have been 3 seconds typing `::VERSION` became 5 minutes looking up the source code and hence this issue.

It could easily be supported just by writing `VERSION = x` and `def version; VERSION; end`.

**Comment by baburdick** [comment]
That's an excellent answer. Thank you for taking the time to detail the reasons.
